source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'STTweetTextView_Example' do
  pod "STTweetTextView", :path => "../"
end

target 'STTweetTextView_Tests' do
  pod "STTweetTextView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
